auto_restart: true
auto_tasks: false
battle_stratege: normal
bn_path: C:/Program Files (x86)/Battle.net/Battle.net.exe
boss_battle_stratege: kill_big
boss_hero:
  BARL_015H:
  - "\u97AD\u7B1E\u8005\u7279\u91CC\u9AD8\u96F7"
  - Trigore the Lashe
  - 1, 2, 3
  - 4
  - '3'
  LETL_019H:
  - "\u74E6\u8389\u62C9\xB7\u6851\u53E4\u7EB3\u5C14"
  - Valeera Sanguinar
  - 1, 2, 3
  - 3
  - '2'
  LETL_030H:
  - "\u8FE6\u987F\u7537\u7235"
  - Baron Geddon
  - 2, 1, 3
  - 0
  - '1'
  LT21_02H:
  - "\u68B5\u59AE\u838E\u8303\u514B\u91CC\u592B"
  - Vanessa Vancleef
  - 1, 2, 3
  - 5
  - '3'
  LT21_07H:
  - "\u5929\u7A7A\u4E0A\u5C09\u7F57\u6770\u65AF"
  - Sky Admiral Rogers
  - 1, 2, 3
  - 2
  - '1'
  SWL_01H:
  - "\u5B89\u4E1C\u5C3C\u8FBE\u65AF"
  - Antonidas
  - 1, 2, 3
  - 1
  - '1'
boss_id: '5'
confidence: 0.8
delay: 0.5
early_stop: false
hero:
  BARL_015H:
  - "\u97AD\u7B1E\u8005\u7279\u91CC\u9AD8\u96F7"
  - Trigore the Lashe
  - 1, 2, 3
  - 5
  - '3'
  LETL_019H:
  - "\u74E6\u8389\u62C9\xB7\u6851\u53E4\u7EB3\u5C14"
  - Valeera Sanguinar
  - 1, 2, 3
  - 2
  - '2'
  LETL_030H:
  - "\u8FE6\u987F\u7537\u7235"
  - Baron Geddon
  - 2, 1, 3
  - 0
  - '1'
  LT21_02H:
  - "\u68B5\u59AE\u838E\u8303\u514B\u91CC\u592B"
  - Vanessa Vancleef
  - 1, 2, 3
  - 4
  - '3'
  LT21_07H:
  - "\u5929\u7A7A\u4E0A\u5C09\u7F57\u6770\u65AF"
  - Sky Admiral Rogers
  - 1, 2, 3
  - 3
  - '1'
  SWL_01H:
  - "\u5B89\u4E1C\u5C3C\u8FBE\u65AF"
  - Antonidas
  - 1, 2, 3
  - 1
  - '1'
hs_log: D:/Program Files (x86)/Hearthstone\Logs\Power.log
hs_path: D:/Program Files (x86)/Hearthstone/Hearthstone.exe
lang: EN-1024x768
lettuce_role_limit: '2'
longest_waiting: 80
ma_decision: visitor_first
map_decision: visitor_first
reward_count_dropdown: '5'
screenshot_error: false
screenshot_reward: false
screenshot_treasure: false
screenshot_visitor: false
stop_at_boss: false
team_id: 2
ui_lang: chs
