auto_restart: false
auto_tasks: false
bn_path: C:/Program Files (x86)/Battle.net/Battle.net.exe
boss_id: 4
confidence: 0.8
delay: 0.5
early_stop: false
hero:
  LETL_001H:
  - "\u5E0C\u5C14\u74E6\u5A1C\u65AF\xB7\u98CE\u884C\u8005"
  - Sylvanas Windrunner
  - 1, 2, 3
  - 5
  LETL_028H:
  - "\u62C9\u683C\u7EB3\u7F57\u65AF"
  - Ragnaros
  - 2, 3, 1
  - 0
  LETL_030H:
  - "\u8FE6\u987F\u7537\u7235"
  - Baron Geddon
  - 2, 3, 1
  - 1
  LETL_041H:
  - "\u5DEB\u5996\u738B"
  - The Lich King
  - 1, 2, 3
  - 4
  SWL_01H:
  - "\u5B89\u4E1C\u5C3C\u8FBE\u65AF"
  - Antonidas
  - 1, 2, 3
  - 2
  SWL_26H:
  - "\u8FEA\u4E9A\u6CE2\u7F57"
  - Diablo
  - 2, 1, 3
  - 3
hs_log: D:/Program Files (x86)/Hearthstone\Logs\Power.log
hs_path: D:/Program Files (x86)/Hearthstone/Hearthstone.exe
lang: EN-1024x768
longest_waiting: 80
reward_count: 5
team_id: 3
ui_lang: chs
