auto_restart: true
auto_tasks: false
battle_stratege: normal
bn_path: C:/Program Files (x86)/Battle.net/Battle.net.exe
boss_battle_stratege: kill_big
boss_hero:
  LETL_030H:
  - "\u8FE6\u987F\u7537\u7235"
  - Baron Geddon
  - 2, 1, 3
  - 1
  - '1'
  LT21_05H:
  - "\u53A8\u5E08\u66F2\u5947"
  - Cooki
  - 1, 2, 3
  - 2
  - '1'
  SWL_01H:
  - "\u5B89\u4E1C\u5C3C\u8FBE\u65AF"
  - Antonidas
  - 1, 2, 3
  - 0
  - '1'
boss_id: '1'
confidence: 0.8
delay: 0.5
early_stop: false
hero:
  LETL_030H:
  - "\u8FE6\u987F\u7537\u7235"
  - Baron Geddon
  - 2, 1, 3
  - 1
  - '1'
  LT21_05H:
  - "\u53A8\u5E08\u66F2\u5947"
  - Cooki
  - 1, 2, 3
  - 2
  - '1'
  SWL_01H:
  - "\u5B89\u4E1C\u5C3C\u8FBE\u65AF"
  - Antonidas
  - 1, 2, 3
  - 0
  - '1'
hs_log: D:/Program Files (x86)/Hearthstone\Logs\Power.log
hs_path: D:/Program Files (x86)/Hearthstone/Hearthstone.exe
lang: EN-1024x768
lettuce_role_limit: '2'
longest_waiting: 80
map_decision: visitor_first
reward_count_dropdown: '3'
screenshot_error: false
screenshot_reward: false
screenshot_treasure: false
screenshot_visitor: false
stop_at_boss: false
team_id: 0
ui_lang: chs
