auto_restart: true
auto_tasks: false
bn_path: C:/Program Files (x86)/Battle.net/Battle.net.exe
boss_id: 0
confidence: 0.8
delay: 0.5
early_stop: false
hero:
  BARL_013H:
  - "\u52A0\u5C14\u9C81\u4EC0\xB7\u5730\u72F1\u5486\u54EE"
  - Garrosh Hellscream
  - 1, 2, 3
  - 3
  BARL_025H:
  - "\u8428\u5C14"
  - Thrall
  - 2, 1, 3
  - 1
  LETL_015H:
  - "\u96F7\u514B\u8428"
  - Rexxar
  - 3, 1, 2
  - 0
  LETL_031H:
  - "\u963F\u83B1\u514B\u4E1D\u5854\u8428"
  - Alexstrasza
  - 1, 2, 3
  - 2
  LT21_01H:
  - "\u827E\u5FB7\u6E29\uFF0C\u8FEA\u83F2\u4E9A\u9996\u8111"
  - Edwin, Defias Kingpin
  - 2, 1, 3
  - 4
  SWL_25H:
  - "\u5409\u5B89\u5A1C\xB7\u666E\u7F57\u5FB7\u6469\u5C14"
  - Jaina Proudmoore
  - 1, 2, 3
  - 5
hs_log: D:/Program Files (x86)/Hearthstone\Logs\Power.log
hs_path: D:/Program Files (x86)/Hearthstone/Hearthstone.exe
is_screenshot: true
lang: EN-1024x768
longest_waiting: 80
reward_count: 5
reward_count_dropdown: '3'
screenshot_error: false
screenshot_reward: false
screenshot_treasure: false
screenshot_visitor: true
team_id: 5
ui_lang: chs
