auto_restart: true
auto_tasks: false
bn_path: C:/Program Files (x86)/Battle.net/Battle.net.exe
boss_id: 4
confidence: 0.8
delay: 0.5
early_stop: false
hero:
  LETL_028H:
  - "\u62C9\u683C\u7EB3\u7F57\u65AF"
  - Ragnaros
  - 2, 3, 1
  - 0
  LETL_030H:
  - "\u8FE6\u987F\u7537\u7235"
  - Baron Geddon
  - 2, 1, 3
  - 1
  LT21_03H:
  - "\u65AF\u5C3C\u5FB7"
  - Sneed
  - 1, 2, 3
  - 3
  SWL_01H:
  - "\u5B89\u4E1C\u5C3C\u8FBE\u65AF"
  - Antonidas
  - 1, 2, 3
  - 2
hs_log: D:/Program Files (x86)/Hearthstone\Logs\Power.log
hs_path: D:/Program Files (x86)/Hearthstone/Hearthstone.exe
lang: EN-1024x768
longest_waiting: 80
reward_count: 5
reward_count_dropdown: '5'
screenshot_error: false
screenshot_reward: false
screenshot_treasure: false
screenshot_visitor: false
team_id: 6
ui_lang: chs
