auto_restart: true
auto_tasks: false
bn_path: C:/Program Files (x86)/Battle.net/Battle.net.exe
boss_id: 0
confidence: 0.8
delay: 0.5
early_stop: false
hero:
  LETL_002H:
  - "\u63D0\u91CC\u5965\xB7\u5F17\u4E01"
  - Tirion Fordring
  - 1, 2, 3
  - 5
  LETL_024H:
  - "\u5C24\u6735\u62C9"
  - Eudora
  - 1, 2, 3
  - 4
  LETL_030H:
  - "\u8FE6\u987F\u7537\u7235"
  - Baron Geddon
  - 2, 1, 3
  - 0
  LETL_037H:
  - "\u66B4\u9F99\u738B\u514B\u9C81\u4EC0"
  - King Krush
  - 1, 2, 3
  - 2
  LT21_01H:
  - "\u827E\u5FB7\u6E29\uFF0C\u8FEA\u83F2\u4E9A\u9996\u8111"
  - Edwin, Defias Kingpin
  - 2, 1, 3
  - 3
  SWL_01H:
  - "\u5B89\u4E1C\u5C3C\u8FBE\u65AF"
  - Antonidas
  - 1, 2, 3
  - 1
hs_log: D:/Program Files (x86)/Hearthstone\Logs\Power.log
hs_path: D:/Program Files (x86)/Hearthstone/Hearthstone.exe
is_screenshot: true
lang: EN-1024x768
longest_waiting: 80
reward_count: 5
reward_count_dropdown: '5'
screenshot_error: false
screenshot_reward: false
screenshot_treasure: false
screenshot_visitor: false
team_id: 3
ui_lang: chs
